# Generated by Django 3.1.6 on 2021-02-18 12:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_flexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='adress',
            field=models.CharField(blank=True, help_text='Заголовок Адреса', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='adress_text',
            field=models.CharField(blank=True, help_text='Адрес офиса', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='company_name',
            field=models.CharField(blank=True, help_text='Название компании', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contacts',
            field=models.CharField(blank=True, help_text='Контакты', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contacts_text',
            field=models.CharField(blank=True, help_text='Текст под Контакты', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='decription',
            field=models.CharField(blank=True, help_text='Описание компании', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.CharField(blank=True, help_text='Заголовок Емэйл', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email_text',
            field=models.CharField(blank=True, help_text='Адрес Емэйл', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_text',
            field=models.CharField(blank=True, help_text='Все права защищены....', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='item1',
            field=models.CharField(blank=True, help_text='пункт меню 1', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='item2',
            field=models.CharField(blank=True, help_text='пункт меню 2', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='item3',
            field=models.CharField(blank=True, help_text='пункт меню 3', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='item4',
            field=models.CharField(blank=True, help_text='пункт меню 4', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone',
            field=models.CharField(blank=True, help_text='Заголовок Телефон', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone_text',
            field=models.CharField(blank=True, help_text='Номер телефона', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social',
            field=models.CharField(blank=True, help_text='Заголовок Соц.Сети', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_links',
            field=models.CharField(blank=True, help_text='Ссылки на соц сети', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_we_can',
            field=wagtail.core.fields.StreamField([('What_we_can', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Фото', required=False)), ('name', wagtail.core.blocks.CharBlock(help_text='Заголовок', required=False)), ('about', wagtail.core.blocks.TextBlock(help_text='Информация', required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_we',
            field=wagtail.core.fields.StreamField([('Why_we', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.CharBlock(help_text='Заголовок', required=False)), ('title', wagtail.core.blocks.CharBlock(help_text='Заголовок', required=False)), ('information', wagtail.core.blocks.TextBlock(help_text='Информация', required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_we_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_form_fields', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
