# Generated by Django 3.1.6 on 2021-02-19 11:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0006_auto_20210218_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='adress_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contacts_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='email_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='phone_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='social_links',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='description',
            field=models.CharField(blank=True, help_text='Заголовок', max_length=255),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='flex_image',
            field=models.ForeignKey(blank=True, help_text='Большое фото', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='footer_text',
            field=models.CharField(blank=True, help_text='Все права защищены....', max_length=255),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='last_text',
            field=models.TextField(blank=True, help_text='Текст внизу'),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='plus_list',
            field=wagtail.core.fields.StreamField([('Plus', wagtail.core.blocks.StructBlock([('plus', wagtail.core.blocks.CharBlock(help_text='Преимущество', required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='pluses',
            field=models.CharField(blank=True, help_text='Что мы предлагаем', max_length=255),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, help_text='Текст после картинки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_title',
            field=models.CharField(blank=True, help_text='Заголовок соц сетей', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contacts',
            field=wagtail.core.fields.StreamField([('Contacts', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Заголовок', required=False)), ('information', wagtail.core.blocks.CharBlock(help_text='Информация', required=False)), ('link', wagtail.core.blocks.URLBlock(help_text='Ссылка (если нужна)', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social',
            field=wagtail.core.fields.StreamField([('Contacts', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Заголовок', required=False)), ('icon', wagtail.core.blocks.CharBlock(help_text='Например: fa-facebook-f/fa-twitter/fa-instagram/fa-linkedin-in', required=False)), ('link', wagtail.core.blocks.URLBlock(help_text='Ссылка (если нужна)', required=False))]))], blank=True, null=True),
        ),
    ]
