# Generated by Django 3.1.6 on 2021-02-19 12:09

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210219_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_title',
            field=models.CharField(blank=True, help_text='Заголовок Контакты', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contacts_text',
            field=models.CharField(blank=True, help_text='Текс под заголовком', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contacts',
            field=wagtail.core.fields.StreamField([('Contacts', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Заголовок', required=False)), ('information', wagtail.core.blocks.TextBlock(help_text='Информация', required=False)), ('link', wagtail.core.blocks.URLBlock(help_text='Ссылка (если нужна)', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='thank_you_text',
            field=models.CharField(blank=True, help_text='Текст после отправки формы обратной связи (Спасибо мы с вами свяжемся....)', max_length=255),
        ),
    ]
